### ISSUE TITLE
Several pagelists?

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#342] opened 2018-10-12 07:20 UTC
Do we need at most one, or several pagelists?

**Comment by iherman** [comment] 2018-10-17 08:32
There does not seem to be an interest to look into this more (and the comments sited in https://github.com/w3c/wpub/issues/342#issuecomment-429230510 are usually negative); propose closing this.

Cc @TzviyaSiegman @wareid @GarthConboy

**Comment by RachelComerford** [comment] 2018-12-03 17:48
Use Case: Educational Texts often come in full and split formats. In these cases a single ebook will use pagelist to reference the page numbering in the Full version of the text (ie Economics) and the splits (ie Microeconomics, Macroeconomics).

**Comment by llemeurfr** [comment] 2018-12-04 12:07
@RachelComerford a page list is "unique" in EPUB, but this notion is already badly (or not) supported in most EPUB UAs. Adding a new layer of complexity, for a theoritical use case, would lead to real issues in practice (non-support or UX/UI issues). Who said that the best is the enemy of the good?

**Comment by TzviyaSiegman** [comment] 2018-12-04 14:50
I would like to confirm that I am understanding things correctly. @RachelComerford is presenting a real-world scenario of a need for multiple page lists. I believe that @llemeurfr and @HadrienGardeur are concerned that this will be challenging to implement, so they are recommending against allowing more than one page-list? Is that correct?

**Comment by HadrienGardeur** [comment] 2018-12-04 14:54
The issue is that it's both challenging to implement AND not widely adopted in EPUB right now even for a single page list.

My initial comment was about page list in general. If you add multiple lists, we get in the same kind of issues as multiple renditions (how do I select the right one?).

What's the expectation from authors in terms of UX?

**Comment by rickj** [comment] 2018-12-04 15:38
I would challenge the _'not widely adopted'_ statement.  That may be true for specific markets, but not as a generalized statement.

**Comment by laudrain** [comment] 2018-12-05 17:59
@RachelComerford:

> Educational Texts often come in full and split formats. In these cases a single ebook will use pagelist to reference the page numbering in the Full version of the text (ie Economics) and the splits (ie Microeconomics, Macroeconomics).

Are "full and split formats" in the same file? I understand the use case when the full version and the spilts are different files, but not quite if it is in a unique file.

**Comment by avneeshsingh** [comment] 2019-01-28 06:42
I have the same question as @laudrain.
Are we talking about two different publications, one is full publication for Economics and one is smaller publication for its part, micro economics.

Or are we talking about a single publication, economics, which contains micro economics part which requires a separate pagelist.
If we are talking about a single publication, does it mean that each part of the publication have its own pagelist starting from page no. 1? i.e. there can be multiple pages with same page number?

**Comment by RachelComerford** [comment] 2019-01-29 13:03
@avneeshsingh @laudrain There are 3 unique print publications. 
Publication 1 - Economics, which has (for example) chapters 1-43.
Publication 2 - Microeconomics: this is made up of Chapters 1-22 of "Economics"
Publication 3 - Macroeconomics: this is made up of Chapter 1, 2, 21-43 of "Economics"

Each of these print books begins on page 1.
There is only one ebook.

So, if chapters 1 and 2 are 10 chapters each. That means in Economics and Microeconomics Chapter 3 begins on Page 20 and in Macroeconomics Chapter 21 begins on Page 20.

This can happen with any course with split semesters - many history courses, economics, some STEM courses... etc.

**Comment by laudrain** [comment] 2019-01-29 13:21
@RachelComerford if I understand well, the single ebook content is Publication 1.
Then in this EPUB, dc:source ISBN is for Publication 1, as source of the main page list.

Publication 2 and Publication 3 have no ebooks counterpart, but their content is in the single ebook of Publication 1.

The issue would then be if the teacher uses the print book Publication 3 - Macroeconomics, and gives a page in that book inside chapter 40 (for instance), someone with the EPUB will not find the correct information in the ebook page-list.
That use case would then need 3 different page-lists, each indexed on one of the 3 different print sources.

**Comment by RachelComerford** [comment] 2019-01-29 14:16
That's absolutely right!

**Comment by mattgarrish** [comment] 2019-01-29 17:52
Do you identify the page locations in the text? If so, how do you disambiguate the multiple publications?

**Comment by HadrienGardeur** [comment] 2019-01-30 10:37
It's probably best to keep this out of the core. Frankly at this point it's not even clear if the ToC will be in the core anyway.

**Closed** 2019-03-18 16:41 UTC
Labels: propose closing, topic:navigation

**Comment by iherman** [comment] 2019-03-18 17:41
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-14).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Several pagelists?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/342">https://github.com/w3c/wpub/issues/342</a><br/>
Wendy Reid: #342: Several pagelists?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/342">https://github.com/w3c/wpub/issues/342</a><br/>
Wendy Reid: and be closed for the core<br/>
… Could be required in an academic profile.<br/>
Avneesh Singh: +1<br/>
Wendy Reid: close.<br/>
Geoff Jukes: +1<br/>
Luc Audrain: +1<br/>
Ivan Herman: +1<br/>
Gregorio Pellegrino: +1<br/>
</details>
