### ISSUE TITLE
Is duration required for audiobooks?

### ISSUE THREAD

**Issue by wareid** [w3c/wpub#420] opened 2019-04-01 18:52 UTC
As discussed in the call on April 1, is top-level duration of an audiobook required? 

Pros:
* Provides UAs with important metadata about the audiobook for processing
* Provides UAs with essential metadata to show user

Cons: 
* Duration metadata can potentially be inaccurate if left to content creator, causing issues for the UA

There might be other pros/cons, but I am leaning towards this being a requirement.

**Comment by llemeurfr** [comment] 2019-04-02 07:33
After internal discussion, we see the interest of having `duration` mandatory. It is not only a descriptive metadata used for display only, but also data used by the user agent to display a timeline for the audiobook (the duration of individual tracks is also really useful in this case, to get the relative size of each track inside the complete timeline).

**Comment by BigBlueHat** [comment] 2019-04-08 16:59
Based on our discussion today, what about this as a proposed option for closing this...

PROPOSAL: use https://schema.org/timeRequired on WP documents (of all kinds) to express expected "duration" of the publication, and continue to use https://schema.org/duration for a more technically accurate expression of length of a MediaObject or Audiobook type specifically.

**Comment by iherman** [comment] 2019-04-09 10:07
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-04-08-pwg.html#section3).

- `RESOLVED:  Move the duration property to web publications`
<details><summary><i class="differentiate">View the transcript</i></summary>
duration in the context of WPUB<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/307">https://github.com/w3c/wpub/issues/307</a><br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/420">https://github.com/w3c/wpub/issues/420</a><br/>
Wendy Reid: duration for entire content vs. duration at the resource level<br/>
Ivan Herman: duration currently defined in audiobook draft - nothing in there for duration is audiobook specific<br/>
… ability to add duration to a resource is generic - doesn’t have to be audio could be video or whatever else<br/>
… does it make sense to have a duration for the book as a whole? for audio books, it is a requirement, but not for a general web publication. but this may not be restricted to audio books. Maybe there could be a video book. The concept is generic, but it may be a requirement for audiobooks and not for general web publications.<br/>
Avneesh Singh: generic, but in audio profile should be compulsory. But what is duration of whole book? Does that include branches that are not included in the reading order?<br/>
Wendy Reid: Never seen a case where resources are not part of the reading order, but it could be possible. So we should include them in the entire duration.<br/>
Brady Duga: what is definition of accurate as far as duration? Want to make sure there is no requirement for the reading system.<br/>
Ivan Herman: what happens today?<br/>
Brady Duga: we determine the duration<br/>
Benjamin Young: agree with duga<br/>
Avneesh Singh: Duration is important metadata<br/>
Marisa DeMeglio: we will need this for sync media too; might not be a precise, e.g. user turns off page number announcements<br/>
Lloyd Rasmussen: agree that the reading system should manage those values<br/>
Ivan Herman: book level duration is more like general advisory information, not necessarily used by user agent for processing.<br/>
… if this is the case, then requiring it to be present sounds like a step too far. Should have/nice to have<br/>
… we have the duration set for an audio or video file. Is it required to provide that info as part of the resource description, or will reading system also ignore that?<br/>
Benjamin Young: <a href="https://schema.org/duration">https://schema.org/duration</a><br/>
Benjamin Young: we use schema.org duration property<br/>
… what is the point on insisting or not insisting… is it a requirement for reading systems? What is the use case we are trying to solve for?<br/>
Wendy Reid: top level duration is useful for user experience, e.g. product detail page. most commonly used on reading system side to break down chapters for example.<br/>
Brady Duga: we won’t use resource level durations but will pre-process all the audio to determine. But a web only reading system may not have this capability.<br/>
Wendy Reid: maybe the metadata is not used, but it can be provided in case the reading system can make use of it<br/>
Avneesh Singh: +1 to move to WP<br/>
Wendy Reid: should we move this to WP since it is not necessarily specific to audiobooks?<br/>
Proposed resolution: Move the duration property to web publications (Wendy Reid)<br/>
Benjamin Young: issue 420 - are we moving the requirement?<br/>
Ivan Herman: the term definition should be generic for WP, then we’ll discuss 420<br/>
Ivan Herman: +1<br/>
Garth Conboy: +1<br/>
Tim Cole: +1<br/>
Bill Kasdorf: +1<br/>
Laurent Le Meur: +1<br/>
George Kerscher: +1q+<br/>
Franco Alvarado: +1<br/>
Ben Schroeter: any opposition to the proposal to move to WP?<br/>
Ben Schroeter: vote<br/>
Ben Schroeter: +1<br/>
Brady Duga: +1<br/>
Avneesh Singh: +1<br/>
Resolution #2: Move the duration property to web publications<br/>
George Kerscher: ivan mentioned attribute about total duration - when a publication is time based media, then the total time would be very useful and I would examine it before downloading an audiobook<br/>
Joshua Pyle: +1<br/>
George Kerscher: like number of pages of a book<br/>
Benjamin Young: duration only allowed on audio books and media, but at the top level for creative works we could use <a href="https://schema.org/timeRequired">https://schema.org/timeRequired</a><br/>
… “estimated time to consume”<br/>
Ivan Herman: sounds like a great match<br/>
Benjamin Young: schema.org/timeRequired = “Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. ‘P30M’, ‘P1H25M’.”<br/>
Wendy Reid: interesting alternative. must think on it.<br/>
Ivan Herman: maybe we could in the WP document we make an explicit reference to time required at the top level and see if we can live with that, and keep the precise resource durations separate<br/>
Bill Kasdorf: +1 to distinguishing between timeRequired and duration<br/>
Wendy Reid: I will add to 420<br/>
George Kerscher: “Approximate reading time”<br/>
</details>

**Comment by iherman** [comment] 2019-04-10 08:49
Note that https://github.com/w3c/wpub/issues/420#issuecomment-480915090 is also affected by the precise definition of duration in the draft, see https://github.com/w3c/wpub/pull/421#issuecomment-481299699 and follow up. _If_ the decision is _not_ to use schema.org's `duration`, then I am not sure we should use schema.org's `timeRequired` either: we have to use a different term defined for publications.

**Comment by marisademeglio** [comment] 2019-04-11 18:19
(Reposting my comment from #421 )

Can we use only one term for duration, and if it's on a resource, it applies to that resource; and if it's at the root-level (along with other publication-wide properties), it applies to the entire publication?

To me, this worked fine and was clear:
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-mediaoverlays.html#example-7

**Comment by geoffjukes** [comment] 2019-04-11 21:48
As I read it `duration` and `timeExpected` are intended to express different things.
`duration` is more appropriate for audio-only audiobooks.
`timeExpected` is more appropriate for Educational publications with exercises/worksheets.

I have tried to follow #421 - there's a lot to digest in there.

For audio-only, the publication-level `duration` would simply be a sum of all the resource-level `duration` values - which is easy to calculate if it is expressed as a float rather than a formatted string.

**Comment by marisademeglio** [comment] 2019-04-12 00:48
At the moment, there is `globalDuration`:
https://raw.githack.com/w3c/wpub/adding-duration/index.html#global-duration

And `totalDuration`:
https://raw.githack.com/w3c/wpub/adding-duration/index.html#dom-linkedresource-totalduration

I think it's confusing to have two terms for such close concepts.

I agree that `timeExpected` feels like an entirely different thing. And, I can see it also applying at resource and publication levels. E.g. a section of a test vs the entire thing.

**Comment by geoffjukes** [comment] 2019-04-12 17:43
I feel that `duration` in seconds (as a double) is the most common way of expressing total runtime of media. See my post in #421

I agree with @marisademeglio. Blackstone's data model has `duration` at the resource level (the run time of the file in seconds), and at the "book" level (the run time of the entire book, alongside the title, narrator, etc)

I do see value in a separate `timeExpected` value for non-media assets (such as quizzes, worksheets etc), but that such a value is subjective and is therefore more akin to 'title' and other metadata. It may be more appropriate to format `timeExpected` differently, as was originally discusses in #421

**Comment by llemeurfr** [comment] 2019-04-12 18:26
If we have a `duration` (whatever the property name) required on each audiobook resource, I don't see the point having also a publication wide property (duration or any other name) defined as "the sum of the resource durations". Computers know how to sum values ;-). 

It's totally different to have a publication wide property expressing an expected reading time experience, which makes sense for any type of publication and is only displayed to the user so that he can choose to start reading a publication is time allows (this is useful in magazine type articles).

**Comment by wareid** [comment] 2019-04-12 18:54
I'm in agreement with Geoff and Marisa on this, I don't love the idea of separating the values or giving them separate names, and I really think it's valuable that we have a total and item-level duration. 

To your point on computers being able to sum values, these files are going to be on the web and packaged for reading systems. A reading system's servers might sum it on ingestion, but a web browser is not going to do the same (it'll increase open time if it needs to process all files then sum them), it's a bad user experience when the information can be easily provided. Remember not all audiobooks will be processed by systems before they're opened, even on a reading system app if a file is brought in externally, why should the app be expected to "create" that information every time a new file is loaded? It's also already a common practise in audiobook metadata, it seems to me we're over-complicating an accepted practice.

**Comment by geoffjukes** [comment] 2019-04-12 18:59
I keep coming back to a subjective `timeExpected` vs the objective `duration`. Maybe there is value in both, in both places, where it is appropriate.

`duration` for media types that have that property (audio, video), and `timeExpected` for where they do not (quizzes etc).

Summing the `duration` and having that in the book-level metadata area makes sense to me too. It's cheap and easy, so why not.

**Comment by wareid** [comment] 2019-04-12 19:07
`timeExpected` does seem worth exploration for WP proper as an item-level value for interactive media types, but maybe not audiobooks.

**Comment by danielweck** [comment] 2019-04-12 19:08
> I feel that `duration` in seconds (as a double) is the most common way of expressing total runtime of media. See my post in #421

And I respectfully disagree :)

https://github.com/w3c/wpub/pull/421#issuecomment-482688407

**Comment by geoffjukes** [comment] 2019-04-12 19:35
so much crossover with #421 😄

**Comment by llemeurfr** [comment] 2019-04-12 20:54
@wareid wrote
> it'll increase open time if it needs to process all files then sum them

It is a misunderstanding: I never proposed to process all files for getting their duration. On the contrary I proposed to require that individual resource durations are set in the manifest. Summing them is therefore a non-brainer for client scripts.

**Comment by geoffjukes** [comment] 2019-04-12 21:16
> Summing them is therefore a non-brainer for client scripts

Agreed, and this was my initial though. I think that a publication-level datapoint (that can be read(at the same time as other publication level datapoints such as title, etc) would be easier on application developers (i.e. it's in the data, so use it).

I definitely think that resource-level duration should be required for time-based media. I still think that this level datapoint should be in seconds. (see https://github.com/w3c/wpub/pull/421#issuecomment-482696746)

**Comment by marisademeglio** [comment] 2019-04-12 21:24
If we end up with several different time format strings, it is at least a pain for the developer to cross-reference those and either find a library or write their own. Perhaps they're writing a component that would otherwise have no requirement on it to do time calculations.

**Comment by geoffjukes** [comment] 2019-04-12 21:35
Publication level `runtime` as an NTP format string
Resource level `duration` in seconds as a double.

**Comment by llemeurfr** [comment] 2019-04-13 07:05
@geoffjukes wrote

> Resource level `duration` in seconds as a double.

But note again that we can't use the schema.org `duration` property as long as schema.org does not accept a decimal value (currently we would have to use "P2M10S" to express 130 sc). This is why Ivan is proposing a **temporary** solution, using a different property name.

**Comment by geoffjukes** [comment] 2019-04-13 18:28
@llemeurfr Thank you for clarifying. I think I'm on the same page finally!

https://schema.org/Audiobook

According to https://en.wikipedia.org/wiki/ISO_8601#Durations (and confirmed in the draft) 130.5 seconds can be expressed as `PT130.5S`. I'd be OK with that.

**Comment by iherman** [comment] 2019-04-16 07:20
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-04-15-pwg#section2-1).

- `RESOLVED:  The time length property (unnamed) will only use a float consisting of the number of seconds of the resource.`
- `RESOLVED:  duration is a descriptive metadata for WP, whose value is the ISO format (as used in schema.org). It is optional.`
- `RESOLVED:  Schema.org duration value is _recommended_ metadata for the audiobooks profile`
<details><summary><i class="differentiate">View the transcript</i></summary>
duration<br/>
Wendy Reid: Issue: <a href="https://github.com/w3c/wpub/issues/420">https://github.com/w3c/wpub/issues/420</a><br/>
Wendy Reid: Open Pull Request: <a href="https://github.com/w3c/wpub/pull/421">https://github.com/w3c/wpub/pull/421</a><br/>
Wendy Reid: should duration be required?<br/>
… duration will become part of the core spec<br/>
Ivan Herman: there are 2 issues<br/>
… one is, if we take duration for one resource, the question that came up was what is the format for the value?<br/>
… one possibility would be to use the ISO 8601 Value, which is used by schema<br/>
… or we could use RFC 7826<br/>
… which is used in the media world<br/>
… the majority seem to favor the RFC value, as it’s more readable than ISO<br/>
… we had an issue #307 a while ago where that was decided, but it wasn’t clean in the doc<br/>
… we can reinforce this decision<br/>
… this is one part of it<br/>
Wendy Reid: I’ve tried to talk to danbri about this, no response yet<br/>
… the RFC value fits better with what we want to do, especially if we also want to reference media fragments<br/>
… can we merge the PR and close this issue?<br/>
Ivan Herman: do we want to make a new resolution, or the already decided one?<br/>
Wendy Reid: let’s stick with the NPT?<br/>
Geoff Jukes: I’m confused about the intent<br/>
… specifying the duration of the resource<br/>
… it’s the file, effectively<br/>
… that duration is only specified in seconds<br/>
… never anything else<br/>
… my concern is that putting in media fragments at the resource level doesn’t make sense<br/>
… if the intent is to conform to schema.org, and we should just use ISO<br/>
… so why NPT instead of using a double?<br/>
… I don’t know why it’s a consideration<br/>
Wendy Reid: media fragments will be a thing, although maybe more in TOC etc than in resources<br/>
Geoff Jukes: that’s not describing a resource, but metadata<br/>
Wendy Reid: we don’t want two different formats for these things<br/>
Geoff Jukes: I disagree<br/>
… and I’m having trouble with these very long discussions<br/>
… I think of a media fragment as a different thing than a resource<br/>
Deborah Kaplan: geoffjukes: +1 for calling out our confusing conversations as confusing. Thanks.<br/>
Ivan Herman: the NPT format is defined in a way that it can have only a number, which is seconds<br/>
… the author may choose to use raw seconds<br/>
Tzviya Siegman: i missed last week. is it possible to summarize the discussion?<br/>
Ivan Herman: in a way we jumped ahead<br/>
… we have make a choice between ISO and RFC<br/>
… then during the discussion a third option became possible, just taking the number of seconds<br/>
… those are the three options<br/>
… so the question is which of the three?<br/>
Geoff Jukes: in addition to that, what is the desire to conform to schema? Is that a design principle?<br/>
Ivan Herman: we want the contents of the manifest to be accessible to the knowledge graph<br/>
… it’s mostly important for bibliographic metadata<br/>
Geoff Jukes: the desire to conform to schema is high, so we can obtain cross-vendor parsing capability<br/>
… is that correct?<br/>
Ivan Herman: yes<br/>
Laurent Le Meur: here we are speaking on duration of resource, not duration of audiobook. It’s not a property of a book.<br/>
… so it’s not tied to a need to express audiobook metadata for schema<br/>
… so we could use seconds, with a name other than duration (like runtime or length)<br/>
… and the audiobook industry would be happy with that<br/>
Geoff Jukes: I’d be happy with a new thing called length or whatever, that’s just a double<br/>
… it’s what we already do<br/>
Ivan Herman: to be clear I am just a messenger<br/>
… whatever the group decides is fine<br/>
Tim Cole: the decision could be made, that in this community we would use duration but constrain the value of seconds<br/>
… i think this is OK<br/>
… it could be enforced via a context document<br/>
… we could also define our own property, and connect it to duration<br/>
… there are ways to express constrained versions of other properties<br/>
Ivan Herman: I don’t think that works<br/>
… schema uses the ISO format, and it doesn’t allow a simple number<br/>
… a number can be a subset of RFC, but not of ISO<br/>
Wendy Reid: the reason we were leaning on RFC it has only two ways to express time, including only seconds<br/>
Ivan Herman: I would propose to move on<br/>
… we define that property to have a value being a float consisting of the number of seconds<br/>
… with a new term like length<br/>
Proposed resolution: The time length property (unnamed) will only use a float consisting of the number of seconds of the resource. (Wendy Reid)<br/>
Ivan Herman: +1<br/>
Laurent Le Meur: +1<br/>
Dave Cramer: +1<br/>
Franco Alvarado: +1<br/>
Tim Cole: +1<br/>
Geoff Jukes: +1<br/>
Joshua Pyle: +1<br/>
Marisa DeMeglio: 0<br/>
Avneesh Singh: +-0<br/>
Avneesh Singh: no strong opinion :)<br/>
… waiting for feedback from media sync people<br/>
Wendy Reid: does this impact sync media<br/>
Marisa DeMeglio: I don’t think so… this is just properties of resources<br/>
Ben Schroeter: +1<br/>
Brady Duga: Abstain (don’t plan to use the value)<br/>
Marisa DeMeglio: this issue doesn’t need to get more complicated<br/>
Resolution #2: The time length property (unnamed) will only use a float consisting of the number of seconds of the resource.<br/>
Ivan Herman: the other issue that came up is more controversial<br/>
… there may be a notion of duration of the whole audiobook<br/>
… it turned out that having that as book-level metadata is something that implementors may ignore<br/>
… they may deduce that from the individual resources<br/>
… but it may be helpful as a hint to the user, as a value in the catalog etc<br/>
… what I did, mostly to generate discussion, was to<br/>
… put a global property there, with the same format<br/>
… primarily defined for a user interface<br/>
… do we need this, or should we remove it from the PR doc?<br/>
Laurent Le Meur: I would say that the audiobook schema.org object supports the duration with ISO 8601<br/>
… it’s there and it’s optional, and it is what we want<br/>
… it’s descriptive metadata<br/>
… we could just adopt this and move on<br/>
Ivan Herman: +1 to laurent<br/>
Geoff Jukes: +1 to laurent<br/>
Wendy Reid: simple descriptive metadata<br/>
Proposed resolution: Schema.org’s Duration will be a required metadata descriptor for audiobooks (Wendy Reid)<br/>
Ivan Herman: +1<br/>
Ben Schroeter: +1<br/>
Laurent Le Meur: I thought the idea was to keep it optional, as in schema.org<br/>
Proposed resolution: Schema.org’s Duration will be a recommended metadata descriptor for audiobooks (Wendy Reid)<br/>
Laurent Le Meur: and it’s a ‘duration’ property (of type ‘Duration’)<br/>
Ivan Herman: +1<br/>
Laurent Le Meur: +1<br/>
Marisa DeMeglio: is this a different property?<br/>
Ivan Herman: yes<br/>
Marisa DeMeglio: -1<br/>
Deborah Kaplan: +1<br/>
Tim Cole: +1<br/>
Joshua Pyle: +1<br/>
Wendy Reid: this is schema.org duration descriptor for audio book, the length of the entire work, the sum of all the parts<br/>
Laurent Le Meur: see <a href="https://schema.org/Audiobook">https://schema.org/Audiobook</a><br/>
Laurent Le Meur: and <a href="https://schema.org/duration">https://schema.org/duration</a><br/>
Geoff Jukes: it’s not the same concept<br/>
… it might be the sum of all resources, but it might be different, for example if there’s non-book audio resources<br/>
Ivan Herman: +1 to geoffjukes<br/>
Geoff Jukes: +1<br/>
Geoff Jukes: so it’s ok to have a different name and format, and it’s good for it to be in schema.org so it’s universally digestable<br/>
Wendy Reid: it would be called duration, it would be the total length of the book, provided by the publisher<br/>
Deborah Kaplan: are we voting on making this required?<br/>
Ivan Herman: there is a mess-up<br/>
… there are 2 things here<br/>
… one is, what is the global descriptive metadata, and what value it takes<br/>
… and the only resolution we are proposing is to use duration with ISO as in schema.org<br/>
… and then there’s the question of whether this metadata item is required<br/>
Geoff Jukes: I would happy for it to be required<br/>
… we have to send it to our publishers/distributors<br/>
Wendy Reid: when I said required I meant for the audiobook profile<br/>
Laurent Le Meur: q for geoffjukes. Why is it required?<br/>
Geoff Jukes: when we send ONIX we include runtime<br/>
… and they like to cross-reference to check they make sure they got the right book<br/>
… if it’s not required we’ll supply it anyway<br/>
Tzviya Siegman: +1 to limited metadata!<br/>
Dave Cramer: The web platform requires very little metadata, we should require the important things (title, author), this does not seem like required metadata<br/>
… I suggest we make it optional<br/>
Ivan Herman: +1 to dauwhe<br/>
Laurent Le Meur: +1 to dauwhe<br/>
Wendy Reid: for an audiobook it’s almost as important as title<br/>
… for a user to understand what they’re getting into<br/>
… to find out if it’s abridged or unabridged<br/>
… or if my phone will keep it<br/>
… I think it should be required<br/>
Ivan Herman: there is no requirement to provide metadata for the number of book pages<br/>
… but the same argument applies, ish<br/>
… I agree it is recommended<br/>
… but “must” is too far<br/>
Tzviya Siegman: I hate to prolong this discussion<br/>
… when we were deciding on EPUB metadata, lots of people said that title should be required<br/>
… but then you get into lots of nuance with what titles means, but most systems don’t pay attention<br/>
… we should look into how systems work with information about length<br/>
… and how this will play out in the real world<br/>
… maybe the implementors can tell us more about this information is used<br/>
Dave Cramer: It strikes me as many of the arguments for the utility of the information is about file size not chronological duration, this information can be useful, but requiring them is not traditionally how the web works<br/>
… we run into issues of validation<br/>
… are we then going to get to a point where validators takes the values and compares them<br/>
… requiring this is complicated<br/>
Laurent Le Meur: I agree on principle we shouldn’t require descriptive metadata<br/>
… and we should keep properties required for user agent functioning or content identification<br/>
… so we should recommend this, underlining all the advantages of using this<br/>
Brady Duga: when considering required metadata, we should ask if it’s impossible to create a book without this metadata.<br/>
… if it’s not impossible, we shouldn’t require it<br/>
Wendy Reid: I’m OK with recommended, even though y’all are completely wrong :)<br/>
Bill Kasdorf: vendors can still require it<br/>
Ivan Herman: we have 2 resolutions to take<br/>
… we never closed the previous resolution<br/>
Proposed resolution: duration is a descriptive metadata for WP, whose value is the ISO format (as used in schema.org). It is optional. (Ivan Herman)<br/>
Ivan Herman: +1<br/>
Tim Cole: +1<br/>
Laurent Le Meur: +1<br/>
Bill Kasdorf: +1<br/>
Deborah Kaplan: +1<br/>
Geoff Jukes: +1<br/>
Ben Schroeter: +1<br/>
Dave Cramer: +1<br/>
Brady Duga: +1<br/>
Garth Conboy: +1<br/>
George Kerscher: +1<br/>
Resolution #3: duration is a descriptive metadata for WP, whose value is the ISO format (as used in schema.org). It is optional.<br/>
Joshua Pyle: +1<br/>
Proposed resolution: Schema.org duration value is recommended metadata for the audiobooks profile (Wendy Reid)<br/>
Ivan Herman: +1<br/>
Laurent Le Meur: +1<br/>
Marisa DeMeglio: +1<br/>
Tim Cole: +1<br/>
Bill Kasdorf: +1<br/>
Ben Schroeter: +1<br/>
Deborah Kaplan: +1<br/>
Resolution #4: Schema.org duration value is _recommended_ metadata for the audiobooks profile<br/>
Wendy Reid: can we move on and never speak of this again?<br/>
Ivan Herman: no<br/>
… I will make the edits according to the resolutions, is it OK to then merge?<br/>
Wendy Reid: +1<br/>
Ivan Herman: and then the PR and the issue can be closed then?<br/>
<b>everyone:</b> YES<br/>
</details>

**Closed** 2019-04-16 18:30 UTC
Labels: topic:audio
