### ISSUE TITLE
Note lack of availability of manifest properties?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#286] opened 2018-07-30 14:56 UTC
Looking specifically at the creators section, many of the listed properties aren't available in CreativeWork (e.g., a lot are from VisualArtwork).

Should we make it clear in the publication types section that the type you choose affects the properties that you can include and/or should this be noted where we list properties from across types?

**Comment by iherman** [comment] 2018-07-31 14:44
Ouch. Yes, I believe we have to. It is actually good, because it gives a better context for those values.

**Comment by HadrienGardeur** [comment] 2018-07-31 14:53
I have mixed feelings about that, this is one of those situations where such restrictions shouldn't IMO apply to what we want to express.

**Comment by iherman** [comment] 2018-07-31 15:46
@HadrienGardeur the problem is that the schema.org processors may reject such manifests. Better bring it to attention in the draft.

**Comment by llemeurfr** [comment] 2018-07-31 16:49
If we say ok to external links in the ToC, let's discuss what the risk is when the publication is offlined. IMO this is not really a technical risk, as all "404" will need to be trapped. 

It's more a UX issue, as a modal box will appear in front of the user, saying something like "This resource can't be accessed offline, join the Web if you want to access it." The user will meet such messages during his navigation in the publication: do we accept that he can face it in the ToC also?

Personally I have nothing strongly against ... As a user I would nevertheless shout at the bloody author who did this to me.

**Comment by iherman** [comment] 2018-08-01 04:42
@llemeurfr Wasn't this comment #276 ?

**Comment by llemeurfr** [comment] 2018-08-01 06:56
For the sake of clarity, let's work from an example: colorist. In schema.org it is a property of VisualArtwork, ComicIssue and ComicStory. All these entities are subtypes of CreativeWork, therefore an use CreativeWork properties. But Book, which is also a CreativeWork, is not a VisualArtwork. Therefore Book cannot use colorist as a property.  

So it's true that, as we want to follow schema.org semantics, one should not find a colorist property in a manifest with type = Book. Such rule may not be enforced in a validation schema, but can be highlighted in the spec for those authors who'd like to get their metadata to be highly semantic.

**Comment by iherman** [comment] 2018-08-01 07:01
@llemeurfr +1, with the additional note (to be put into the document) that schema.org processors may not accept those metadata in case the type used is wrong. After all, it is also in the authors' interest to be friendly towards those engines...

**Comment by laudrain** [comment] 2018-08-01 07:08
But for Bandes Dessinées, Comics, Manga, we need Colorist! 
These CreativeWorks are Books and also VisualArtwork.
Isn't there a proper syntaxic way to borrow Colorist property to VisualArtwork for Book?

**Comment by laudrain** [comment] 2018-08-01 07:35
This answers my concern.
Cannot we already use it as a standard JSON-LD construction ?

**Comment by llemeurfr** [comment] 2018-08-01 07:36
et voilà, multiple inheritence coming ... can become tricky if we don't look closely at side effects. 

@laudrain comics ... (visual narratives) seem to be classified as ComicStory (subtype of VisualArtwork) in schema.org. https://bib.schema.org/ComicStory

**Comment by laudrain** [comment] 2018-08-01 07:43
And ComicStory has artist, colorist, inker, letterer, penciler properties.
Then shouldn't we think about a Comics WP having a schema.org "ComicStory" in the first place instead of a "Book" type ?

**Comment by llemeurfr** [comment] 2018-08-01 07:57
It would make sense. THe only think that bothers me is the definition of ComicsStory in schema.org: "The term "story" is any indivisible, re-printable unit of a comic, including the interior stories, covers, and backmatter. **Most comics have at least two stories: a cover (ComicCoverArt) and an interior story.**"
We want to express the notion of "Comic Book" with no differentiation btw cover and interior. I don't quite understand why there is this split in the definition. A clarification from the creators of this entity would be useful.

**Comment by iherman** [comment] 2018-08-01 08:34
Let us separate two things.

1. I am sure the current categorization of publications in schema.org can be improved. I would think trying to talk to schema.org, possibly adding categories or improving the definition of new ones, is a clear possibility that we should explore.

2. (answering @laudrain)  the "standard" JSON-LD possibility would be to use `@type` with an array of types. schema.org was originally based on microdata, which does not have multiple types, hence the introduction of [additionalType](https://schema.org/additionalType). However (to my surprise, b.t.w.) it seems that the google structured data testing tool does accept the standard JSON-LD construction: 

```
{
  "@context":  "http://schema.org/",
  "@id": "#record",
  "@type": ["Book","VisualArtwork"],
  "colorist" : "somebody"
}
``` 

is accepted. Ie, we have two choices

i. Use the standard JSON-LD construction as above
ii. Use the "additionalType" approach

I would be in favor of (i) then...

**Comment by laudrain** [comment] 2018-08-01 09:34
Very interesting. I'm also in favor of (i).
It looks like this has already been addressed in bib.schema.org.
Why not use it?

**Comment by HadrienGardeur** [comment] 2018-08-01 09:37
IMO, including multiple types falls into the realm of "good authoring" but this is not something that we should require.

In a future "WP check", this should trigger a warning, not an error.

**Comment by iherman** [comment] 2018-08-01 10:08
Unfortunately, it may not be a matter of good authoring practice only, again if the google structured data tool is determining factor.

While

```
{
"@context" : "https://schema.org",
"@type" : ["Book", "VisualArtwork"],
"artist": "Somebody",
"illustrator": "Somebody else"
}
```

is indeed accepted, neither

```
{
"@context" : "https://schema.org",
"@type" : ["VisualArtwork"],
"artist": "Somebody",
"illustrator": "Somebody else"
}
```

nor

```
{
"@context" : "https://schema.org",
"@type" : ["Book"],
"artist": "Somebody",
"illustrator": "Somebody else"
}
```

are. The first is rejected because `illustrator` is defined for books only, whereas the second because `artist` is only valid for visual artworks.

:-(

**Comment by llemeurfr** [comment] 2018-08-01 10:24
@iherman, this is our choice: either we state that positive semantic validation (e.g. via google structured data tool) is required, or we state that it is good practice only.
 
Said differently, either EPUBCheck v4 has a JSON schema validation step + a semantic validation step, or it has only a JSON schema validation step. 

I've got mixed feelings about that matter: as we are using a semantic aware structure, I'd prefer a semantic validation of publications. But it has a large practical impact: the google tools are not perfect, they are online only (bad for an EPUB check).

**Comment by iherman** [comment] 2018-08-01 11:50
@llemeurfr, true. However, even if we state that validation via google structured data tool is _not_ required (ie, we can accept to be lax on that), I think the document must make it clear that if those are not followed, the metadata may not be understood by search engines. This sounds to me as something "heavier" than just "good authoring".

**Comment by laudrain** [comment] 2018-08-01 12:05
Even if we don't require it, our specs should not make it impossible for the manifest to be valid re google structured data tools.

**Comment by iherman** [comment] 2018-08-01 12:50
@laudrain that is for sure: it should not make it impossible.

In the very specific case, what we have to do is something like:

1. Each creator property should list the types for which the that property is valid per schema.org
2. Make it explicit that _if_ the author cares about the google schema.org validity then the author _SHOULD_ list them all in the `@type` of the publication.
3. Using at least one type (`CreativeWork`, in its most general case) is a _MUST_.

@mattgarrish does that answer your original question? 

@mattgarrish @laudrain @HadrienGardeur @llemeurfr is that o.k.?

**Comment by llemeurfr** [comment] 2018-08-01 12:53
It's ok for me, knowing that such rule must stand for all metadata properties, not only creators.

**Comment by mattgarrish** [comment] 2018-08-01 13:06
> Make it explicit that if the author cares about the google schema.org validity

Well, I think _we_ should care about schema.org validity if we're proposing a manifest that uses schema.org metadata. :)

But I'm perfectly fine saying that we have permissive processing rules and that user agents should compile into the infoset properties that may not be technically valid per any given schema.org type. That's just a variation on what you propose, though.

> Each creator property should list the types for which the that property is valid per schema.org

Maybe if we phrase this as "defined in", but listing every type could prove a nightmare given inheritance of properties.

**Comment by iherman** [comment] 2018-08-01 13:10
> Maybe if we phrase this as "defined in", but listing every type could prove a nightmare given inheritance of properties.

+1 to that!

**Closed** 2018-08-10 09:16 UTC
Labels: topic:manifest
