### ISSUE TITLE
Processing our manifest into WebIDL

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#268] opened 2018-07-10 10:56 UTC
There's a pretty large gap in our current draft: we don't describe at all how the manifest should be parsed and processed.

- for some items (`url`, `dateModified`, `datePublished` and `readingProgression`) this is a straightforward conversion from JSON
- for `id`/`@id` we need to define which term has the priority and what happens when both are present
- for `name`, we need to check whether a string or an object (`@value` + `@language`) is used and parse it accordingly in `LocalizableString`
- the default language also requires some additional processing since we need to extract it from the context definition
- all creators require that we:
  - check if we have a single object/string or an array
  - parse both the string and object (with `name`) forms
  - handle `name` as well (string or `@value` + `@language`)
  - store the role somehow (TBD)
- for all structural properties that use links (`readingOrder`, `resources` and `links`):
  - support both strings (URL) or objects
  - define a default `encodingFormat` when using a string? (TBD)
  - support both string and array of strings for `rel`
  - support both string and object (`@name` + `@language`) form for `name` and `description`
- the table of contents require its own section since it's even more complex than the rest:
  - identify where the TOC is located by searching for `contents` in `readingOrder` and `resources`
  - fallback to the entry page if no reference is found
  - fetch and parse the HTML document
  - extract the TOC from HTML and populate the WebIDL
- accessibility is TBD since we haven't defined WebIDL for it yet

We also need to decide how this will be organized in the spec. Do we express processing requirements along the [manifest expression](https://w3c.github.io/wpub/#wp-properties)? Under the [lifecycle section](https://w3c.github.io/wpub/#wp-lifecycle)? In the [appendix for the WebIDL](https://w3c.github.io/wpub/#webidl)?

**Comment by HadrienGardeur** [comment] 2018-07-10 11:51
Overall this will be fairly "heavy", but this is the price we have to pay for the flexibility when authoring JSON-LD + schema.org.

**Comment by iherman** [comment] 2018-07-18 09:11
@HadrienGardeur yes, the IDL and, mainly, the processing has to be updated along the lines of what you describe. 

I would, however, propose not to do it right now. I would think that the draft should be published by adding an editorial note into the document making it clear that the IDL + processing is out of date and this is one of the next steps to do. Once published, and giving the schema.org part some rest (and expect external comments) we can do the changes. @mattgarrish wdyt?

**Comment by iherman** [comment] 2018-07-18 09:20
@HadrienGardeur on the technical aspect of your comments: I wonder whether, in the processing description (and, actually, the implementation), we should rely on the [expansion API of the JSON-LD standard](https://www.w3.org/TR/2014/REC-json-ld-20140116/#expanded-document-form). In other words, the first step (after getting hold of the manifest) is to run the JSON-LD through the expansion and pick up after that. As the standard says, the expansion will make the context files disappear...

I am not saying it will solve all our issues, but:

- all values will be stored as objects; if they were originally strings, they will be objects of the form `{ "@value" : "whatever" }` with, possibly, the language tag added
- every value will be an array, so we do not have to check that; if it is a list, it will have a `"@list"` property
- overall, that form can be considered as some sort of a "canonical" form for processing, which may make the description (and, I guess, the implementation) of the manifest much clearer.

WDYT?

**Comment by iherman** [comment] 2018-07-18 09:24
As an example, this is the expanded form of [one of the examples in the document](https://w3c.github.io/wpub/#single-document-publication): 

```
[
  {
    "@type": [
      "http://schema.org/CreativeWork"
    ],
    "http://schema.org/copyrightHolder": [
      {
        "@value": "World Wide Web Consortium"
      }
    ],
    "http://schema.org/copyrightYear": [
      {
        "@value": "2015"
      }
    ],
    "https://schema.org/creator": [
      {
        "@list": [
          {
            "@type": [
              "http://schema.org/Person"
            ],
            "http://schema.org/name": [
              {
                "@value": "Jeni Tennison"
              }
            ]
          },
          {
            "@type": [
              "http://schema.org/Person"
            ],
            "http://schema.org/name": [
              {
                "@value": "Gregg Kellogg"
              }
            ]
          },
          {
            "@type": [
              "http://schema.org/Person"
            ],
            "http://schema.org/name": [
              {
                "@value": "Ivan Herman"
              }
            ]
          }
        ]
      }
    ],
    "http://schema.org/datePublished": [
      {
        "@type": "http://schema.org/Date",
        "@value": "2015-12-17"
      }
    ],
    "@id": "http://www.w3.org/TR/tabular-data-model/",
    "https://www.w3.org/ns/wp#resources": [
      {
        "@value": "datatypes.html"
      },
      {
        "@value": "datatypes.svg"
      },
      {
        "@value": "datatypes.png"
      },
      {
        "@value": "diff.html"
      },
      {
        "@value": "test-utf8.csv"
      },
      {
        "@value": "test-utf8-bom.csv"
      },
      {
        "@value": "test-utf16.csv"
      },
      {
        "@value": "test-utf16-bom.csv"
      },
      {
        "@value": "test.xls"
      },
      {
        "@value": "test.xlsx"
      }
    ],
    "http://schema.org/url": [
      {
        "@id": "http://www.w3.org/TR/2015/REC-tabular-data-model-20151217/"
      }
    ]
  }
]
```

**Comment by iherman** [comment] 2018-07-18 09:31
@HadrienGardeur I am not sure. UA-s may ignore JSON-LD, in some sense, just use (available) JS libraries to perform expansion. I would certainly not implement expansion myself.

**Comment by HadrienGardeur** [comment] 2018-07-18 09:32
@iherman I'm worried about the overhead. It's not ideal to implement the processing manually, but there might be a real overhead (and/or a lack of libraries available in a given language) with the JSON-LD expansion API.

**Comment by iherman** [comment] 2018-07-18 09:36
I understand... let us see what other implementers may say!

**Comment by llemeurfr** [comment] 2018-07-18 10:03
As a developer, looking at parsing a JSON structure to create an in-memory model, I would only expand the JSON-LD serialization if to do that I can find a great/well-maintained OSS lib for my favorite language (and here we could list more than 20 languages). It would be great but __I doubt it will be the case__.  And after that, I would still have to map this structure to my in-memory model. 

Currently, we parse "by hand" the structure, as the simple JSON decoding feature or our favorite languages don't work with the polymorphic structure of the Webpub manifest.  It's boring but direct. And the native JSON decoding feature of my language would not make a clean object from the expanded JSON-LD structure neither, so this unmarshalling would still be boring.

**Comment by iherman** [comment] 2018-07-18 10:15
Yeah... I have to accept all these arguments, it is still a pity, though. Relying on the compaction would make the manifest more future proof, too. For example, as of today, we cannot use the handy language map feature, because (afaik) no schema.org processor recognizes it. However, if they do tomorrow, we should then explicitly expand the processing of the manifest to include language maps to make it (standard wise) usable, whereas the expansion algorithm would handle that feature automatically, too.

Anyway... it sounded like a good idea:-)

**Comment by iherman** [comment] 2018-08-14 05:25
I believe that the specific questions raised in this have been covered by the [latest draft](https://www.w3.org/TR/2018/WD-wpub-20180814/), the updates on the JSON-Schema, the [conversion p.o.c implementation](
https://lists.w3.org/Archives/Public/public-publ-wg/2018Aug/0004.html) and some explicit issues. @HadrienGardeur @llemeurfr  would it be o.k. to close this issue and, if I missed any open problem, raise it as a specific issue?

(Knowing that [Section 5 of the draft](https://w3c.github.io/wpub/#wp-lifecycle) on the Lifecyle still needs update of course.)

**Comment by llemeurfr** [comment] 2018-08-14 06:54
Good for me

>. @HadrienGardeur @llemeurfr would it be o.k. to close this issue and, if I missed any open problem, raise it as a specific issue?

**Comment by iherman** [comment] 2018-08-14 13:31
@HadrienGardeur (admin) I would prefer to push this into a separate issue, it is hard to handle an issue that has, in fact, several topics.

Could you open this separately and then close the present issue?

**Comment by HadrienGardeur** [comment] 2018-08-14 13:32
... but this is exactly what this issue is all about, why should we open the same one elsewhere?

**Comment by iherman** [comment] 2018-08-14 13:59
As you said: there is the high level question (
https://github.com/w3c/wpub/issues/268#issuecomment-412870290) which is really at the bases. But if you prefer to keep this one issue open, that is fine with me...

**Comment by iherman** [comment] 2018-08-14 14:02
As for the question in 
https://github.com/w3c/wpub/issues/268#issuecomment-412870290: in my view, a refresh of the lifecycle session is the best option. The details of the algorithms may not be 100% detailed, ie, it is not a code reengineering into English; we will have to find the right style.

I was considering giving a go at it based on the p.o.c. work I did, unless somebody beats me into it...

**Comment by iherman** [comment] 2018-08-14 15:36
Yep... it is indeed not that simple. I was a bit too fast:-(

The problem is how to describe things in a language independent manner. If it was a matter of describing things in, say, JavaScript, than the p.o.c. implementation works and takes care of many things behind the screens.

My current thoughts are (comments welcome...)

1. We define a (conceptual!) pre-processing in terms of a JSON-to-JSON transformation. That describes things like transforming all values into arrays (when appropriate), strings into `@value`+`@language` structures (for now, with #299 pending), names into Persons for creators, etc.
1. As part of the same pre-processing steps, we describe issues like
	* using the `<title>` element as a `name` in case the latter is not available
	* adding an `inLanguage` property if the manifest is in a `<script>` and the language is set in the HTML
	* some other default actions I may forget…
1. Much like it is done in the current draft, but also in the [WebApp Manifest](https://www.w3.org/TR/appmanifest/#webappmanifest-dictionary) by:
	* "Let `manifest` be the result of converting json to a <code>WebPublicationManifest</code> dictionary" 
	* "set `manifest["url"]` be the result of converting `manifest["url"]` into an absolute URL using the base URL" (or something like that
	* etc.


How does that sound?

**Comment by HadrienGardeur** [comment] 2018-08-14 16:07
I think this sounds good: it's a canonical version of our manifest. We'll need to be careful though about how everything is named in our WebIDL (including `@value` and `@language`).

**Comment by iherman** [comment] 2018-08-15 14:11
@HadrienGardeur @mattgarrish I have created #306 that contains now a section on a canonical manifest (thanks for the term, @HadrienGardeur, it is perfect!)

I would propose to follow the discussion on the PR, we can make use of the PR facilities of direct comment and automatically generated diffs (that is why I already created a PR, although much work is still to be done).

**Comment by TzviyaSiegman** [comment] 2018-10-10 15:21
@HadrienGardeur @mattgarrish @iherman OK to close?

**Comment by iherman** [comment] 2018-11-08 05:44
The canonicalization is now inherent part of the draft. Closing...

**Closed by iherman** 2018-11-08 05:44 UTC
Labels: propose closing
