### ISSUE TITLE
For manifest in FPWD: Should manifest TITLE be Required per WCAG 2?

### ISSUE THREAD

**Issue by Ryladog** [w3c/wpub#30] opened 2017-08-14 17:02 UTC
https://rawgit.com/w3c/wpub/manifest-consensus-proposal/index-manifest-proposal.html#abstract-versus-concrete-manifest

**Comment by lrosenthol** [comment] 2017-08-15 00:59
I assume the relevant part of WCAG is this - https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

If so, I would argue that there is *nothing* there that requires a title in a web publication itself.  Only in the actual content documents that make up the WP.

**Comment by iherman** [comment] 2017-08-15 04:18
Admin comment: this sounds like a duplicate of issue #20. @Ryladog, I would prefer to close this, referring back to that one; would you agree?

**Comment by avneeshsingh** [comment] 2017-08-16 10:47
My understanding is that WP requires the title. WCAG 2.0 don't mention manifest in the SC or techniques at 1.
I think that it is up to us to figure out how this WCAG 2.0 requirement can be met, and then recommend the technique in WCAG 2.1.


1.
http://www.w3.org/WAI/WCAG20/quickref/20070517/Overview.php#navigation-mechanisms-title

**Comment by TzviyaSiegman** [comment] 2017-08-28 17:19
This issue is resolved with https://github.com/w3c/wpub/pull/51

**Closed by TzviyaSiegman** 2017-08-28 17:19 UTC
Labels: topic:accessibility, topic:manifest

**Comment by iherman** [comment] 2017-08-29 05:00
See [telco discussion](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-08-28-minutes#section3) on closure.
